tasker/config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'

  get '/tasks' => 'tasks#index'
  post '/tasks' => 'tasks#create'
  get '/users' => 'tasks#admin'
  get '/users/:id' => 'tasks#show', as: :user_task

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  end

tasker/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

tasker/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	after_initialize :set_default_role
	has_many :tasks

	def to_h
		{name: self.name, email: self.email}
	end


	private
	def set_default_role
		self.role ||= 'user'
	end
end

tasker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end

  def authorize
  	if current_user.nil?
  		redirect_to login_path, notice: "This view is protected"
  	end
  end

end

tasker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		#no need for input
	end

	def create
		@email = params[:email] #for when the page refreshes after failure - the email field is already filled (see the login_path form)
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end
end

tasker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authorize
	before_action :admin_only, only: [:admin, :show]

	def index
		@tasks = current_user.tasks
		@task  = Task.new
	end

	def admin
		@users = User.all
	end

	def show
	end

	def create
		#binding.pry

		@task = current_user.tasks.new(task_params)
		if @task.save
			redirect_to root_path
		else
			render :index
		end
	end

	def show
	    task = Task.find_by(id: params[:id])
		unless task
		render json: {error: "task not found"},
		status: 400
		return
		end
	end

	def update
	    task = Task.find_by(id: params[:id])
		unless task
		render json: {error: "task not found"},
		status: 400
		return
		end
		task.update(task_params)
		#render json: task
	end

	def destroy
	    task = Task.find_by(id: params[:id])
		unless task
		render json: {error: "task not found"},
		status: 400
		return
		end
		task.destroy
		#render json: task
 	end

	private
	def task_params
		params.permit(:name, :completion_date, :status)
	end

	def admin_only
		if current_user.role != 'admin'
			redirect_to tasks_path, alert: 'Access denied'
		end
	end
end

tasker/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :new
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

tasker/app/helpers/application_helper.rb
module ApplicationHelper
end

tasker/app/helpers/sessions_helper.rb
module SessionsHelper
end

tasker/app/helpers/tasks_helper.rb
module TasksHelper
end

tasker/app/helpers/users_helper.rb
module UsersHelper
end

tasker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Tasker</h1>
<h2>Taskly's Cheeky Cousin</h2>
<% if current_user.nil? %>
<p>no current user</p>
<%= link_to 'Login', login_path %>
<%= link_to 'Signup', signup_path %>
<% else %>
<p>Hello, you are logged in as <%= current_user.name %>!</p>
<%= link_to 'Logout', logout_path %>
<% end %>

<% flash.each do |name, message| %>
 <p><%= message %></p>
<% end %>

<%= yield %>

</body>
</html>

tasker/app/views/tasks/admin.html.erb
<h1>ADMIN PAGE: for admins only</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to 'See details', user_task_path(user.id) %>
			<%= user.name %> - <%= user.role %>
			<ul>
				<% user.tasks.each do |task| %>
					<li><%= task.name %></li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

tasker/app/views/tasks/index.html.erb
<h1>Task Index Page</h1>

<ul>
	<% @tasks.each do |task| %>
		<li><%= task.name %></li>
	<% end %>
</ul>


<%= form_for :task, url: tasks_path do |f| %>
Task name: <%= f.text_field :name %>
Deadline: <%= f.date_field :completion_date %>
Status: <%= f.text_field :status %>

<%= f.submit "Submit" %>
<% end %>

tasker/app/views/users/new.html.erb
<h1>Signup Form</h1>

<% if @user.errors.any? %>
	<ul>
	<% @user.errors.messages.each do |k, v| %>
		<li><%= v %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for :user, url: users_path do |f| %>
Name: <%= f.text_field :name %>
Email: <%= f.text_field :email %>
Password: <%= f.password_field :password %>
Password Confirmation: <%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>
<% end %>